from turtle import*
t = Turtle()
wn = Screen
title("MY WORLD")
bgcolor("pink")
t.shape("triangle")
t.color("red", "yellow")
t.hideturtle()
t.speed(1)
t.begin_fill()
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.end_fill()
done()